# Workflow for syncing CSV labels to GitHub Labels
name: .Platform - Sync repo labels from CSV

on:
  schedule:
    - cron: 45 11 * * * # Run daily at 3:45 AM PST
  workflow_dispatch: {}

# Allow one concurrent deployment
concurrency:
  group: "labels"
  cancel-in-progress: true

permissions:
  issues: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - name: Sync AVM Labels To Repos GitHub Labels
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/Azure-Verified-Modules/main/docs/static/scripts/Set-AvmGitHubLabels.ps1" -OutFile "./Set-AvmGitHubLabels.ps1"
          ./Set-AvmGitHubLabels.ps1 -RepositoryName "${{ github.repository }}" -CreateCsvLabelExports $false -RemoveExistingLabels $false -NoUserPrompts $true
